<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MonopolyCore\MonopolyCore.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Imágenes opcionales del tablero: todo lo que esté en la carpeta Imagenes se copia junto al .exe -->
  <ItemGroup>
    <None Include="Imagenes\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>